<?php

return [
    'ar' => [
        'name' => 'الاسم',
        'username' => 'اسم المُستخدم',
        'email' => 'البريد الالكتروني',
        'pin_code' => 'كود التفعيل',
        'first_name' => 'الاسم الأول',
        'last_name' => 'اسم العائلة',
        'password' => 'الرقم السرى',
        'old-password' => 'الرقم السرى الحالى',
        'password_confirmation' => 'تأكيد الرقم السر',
        'city' => ' حقل المدينة',
        'country' => 'حقل الدولة',
        'country_id' => 'حقل الدولة',
        'address' => 'عنوان السكن',
        'phone' => 'الهاتف',
        'mobile' => 'الجوال',
        'age' => 'العمر',
        'sex' => 'الجنس',
        'gender' => 'النوع',
        'title' => 'العنوان',
        'content' => 'المُحتوى',
        'description' => 'الوصف',
        'excerpt' => 'المُلخص',
        'date' => 'التاريخ',
        'time' => 'الوقت',
        'city_id' => ' المدينة',
        'photo' => '  الصورة',
        'rate' => ' التقييم',
        'state_id'              => 'البلد',
        'graduate_year'         => 'سنه التخرج',
        'gender'                => 'النوع',
        'faculty'               => 'الكليه',
        'major'                 => 'الرئيسي',
        'qualification_id'      =>'المؤهل',
        'b_day'                 =>'تاريخ الميلاد',
    ],
    'en' => [
        'name'                  => 'name'                 ,
        'username'              => 'username'             ,
        'email'                 => 'email'                ,
        'pin_code'              => 'pin_code'             ,
        'first_name'            => 'first name'           ,
        'last_name'             => 'last name'            ,
        'password'              => 'password'             ,
        'old-password'          => 'old password'         ,
        'password_confirmation' => 'password confirmation',
        'city'                  => 'city'                 ,
        'country'               => 'country'              ,
        'country_id'            => 'country'              ,
        'address'               => 'address'              ,
        'phone'                 => 'phone'                ,
        'mobile'                => 'mobile'               ,
        'age'                   => 'age'                  ,
        'sex'                   => 'sex'                  ,
        'gender'                => 'gender'               ,
        'title'                 => 'title'                ,
        'content'               => 'content'              ,
        'description'           => 'description'          ,
        'excerpt'               => 'excerpt'              ,
        'date'                  => 'date'                 ,
        'time'                  => 'time'                 ,
        'city_id'               => 'city'                 ,
        'photo'                 => 'photo'                ,
        'rate'                  => 'rate'                 ,
        'state_id'              => 'state'                ,
        'graduate_year'         => 'graduate year'        ,
        'gender'                => 'gender'               ,
        'faculty'               => 'faculty'              ,
        'major'                 => 'major'                ,
        'qualification_id'      => 'qualification'         ,
        'b_day'                 => 'birth day'             ,
    ],
];




